sudo: required

language: c

services:
  - docker

before_install:
# build simulation server image
- docker build -t takawang/modbus-server tests/mbserver/.
# build zclient image
- docker build -t takawang/modbus-zclient tests/zclient/.
# build modbusd image
- docker build -t takawang/modbusd .

script:
- docker run -d -P --name slave takawang/modbus-server
- docker run -v /tmp:/tmp -d -P --name modbusd --link slave:slave  -it takawang/modbusd /bin/sh -c "./modbusd ../modbusd.json"
# docker run -v /tmp:/tmp --link slave:slave -it takawang/modbus-zclient /bin/bash