sudo: required

language: c

services:
  - docker

before_install:
# build simulation server
- docker build -t takawang/modbus-server tests/mbserver/.
# build zclient
- docker build -t takawang/modbus-zclient tests/zclient/.
# Install depends
- docker build -t takawang/modbusd .

script:
# run modbus simulation server
- docker run -p 502:502 -d takawang/modbus-server
#docker run -v /tmp:/tmp -it takawang/modbus-zclient /bin/bash
