sudo: required

language: c

services:
  - docker

before_install:
- docker pull takawang/modbus-server
- docker run -p 502:502 -d takawang/modbus-server
- docker pull takawang/modbus-zclient
#docker run -v /tmp:/tmp -it takawang/modbus-zclient /bin/bash
- docker pull takawang/modbusd
- docker ps -a