slave:
    build: tests/mbserver/.

zclient:
    build: tests/zclient/.
    volumes_from:
        - modbusd
    links:
        - slave
    
modbusd:
    build: .
    volumes:
        - /tmp:/tmp
    links:
        - slave
