slave:
    build: tests/mbserver/.

zclient:
    build: tests/zclient/.
    volumes_from:
        - modbusd
    links:
        - slave
    
modbusd:
    build: .
    volumes:
        - /tmp:/tmp
    links:
        - slave
    command: valgrind --leak-check=full /usr/bin/modbusd /etc/modbusd/modbusd.json
