slave:
    build: tests/mbserver/.
    
modbusd:
    build: .
    volumes:
        - /tmp:/tmp
    links:
        - slave
zclient:
    image: tests/zclient/.
    volumes_from:
        - modbusd
    links:
        - slave